FROM php:7.4.16-fpm-alpine3.13

COPY ./lib/composer.phar /tmp/composer.phar
COPY ./lib/redis-5.2.0.tgz /tmp/redis-5.2.0.tgz
COPY ./lib/swoole-4.5.7.tgz /tmp/swoole-4.5.7.tgz
COPY ./lib/amqp-1.10.2.tgz /tmp/amqp-1.10.2.tgz
COPY ./lib/mongodb-1.7.5.tgz /tmp/mongodb-1.7.5.tgz
COPY ./lib/rabbitmq-c-0.9.0-master.tar.gz /tmp/rabbitmq-c-0.9.0-master.tar.gz

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache git wget openssl openssl-dev libstdc++ cmake build-base \
    && cd /tmp \
    && tar -zxvf redis-5.2.0.tgz \
    && tar -zxvf swoole-4.5.7.tgz \
    && tar -zxvf amqp-1.10.2.tgz \
    && tar -zxvf mongodb-1.7.5.tgz \
    && tar -zxvf rabbitmq-c-0.9.0-master.tar.gz \
    && cd rabbitmq-c-0.9.0-master \
    && mkdir build \
    && cd build \
    && cmake .. \
    && cd .. \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/rabbitmq-c \
    && cmake --build . --target install \
    && mv /usr/local/rabbitmq-c/lib64 /usr/local/rabbitmq-c/lib \
    && cd .. \
    && docker-php-source extract \
    && mv redis-5.2.0 /usr/src/php/ext/redis \
    && mv swoole-4.5.7 /usr/src/php/ext/swoole \
    && mv amqp-1.10.2 /usr/src/php/ext/amqp \
    && mv mongodb-1.7.5 /usr/src/php/ext/mongodb \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
    && docker-php-ext-configure swoole --enable-openssl --enable-http2 \
    && docker-php-ext-configure amqp --with-librabbitmq-dir=/usr/local/rabbitmq-c \
    && docker-php-ext-install bcmath sockets redis mongodb swoole pdo_mysql amqp \
    && mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && rm -rf redis-5.2.0.tgz swoole-4.5.7.tgz amqp-1.10.2.tgz mongodb-1.7.5.tgz rabbitmq-c-0.9.0-master.tar.gz rabbitmq-c-0.9.0-master \
    && docker-php-source delete \
    && mkdir /www

# 安装gd库
# apk add libpng-dev freetype-dev libjpeg-turbo-dev
# docker-php-ext-install -j$(nproc) gd

WORKDIR /www

EXPOSE 9000